require 'slack-ruby-bot'
require 'slack_rickbot/commands/team'
require 'slack_rickbot/commands/github'
require 'slack_rickbot/commands/rick'
require 'slack_rickbot/commands/morty'
require 'slack_rickbot/bot'
